name: 'Verify PR'

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            release
            build
          wip: true
          scopes: R-[0-9]+
          requireScope: true